#!/bin/sh

read -p "Name of the project:" projname

srcpath="$( cd "$( dirname "$0" )" && pwd )"
projpath="$srcpath/Projects"
copypath="$projpath/$projname"

if [ ! -d "$copypath" ]; then
	echo "Creating folder"
	mkdir -p "$copypath"
fi

echo "Copying files"
touch "$copypath/main.cpp"
echo "#define CAC_PROJ_NAME \"$projname\"" >> "$copypath/main.cpp"
cat "$srcpath/to_copy/main.cpp" >> "$copypath/main.cpp"
cp "$srcpath/to_copy/.gitignore" "$copypath"
cp "$srcpath/to_copy/Makefile" "$copypath"
ln -s "$srcpath/src/Cacao" "$copypath/Cacao"
echo "Done."
