//Copyright camila314 & alk1m123 2021. Autogenerated using a python script
#pragma once // but if u want it to be more crossplatform. u need to use c standard.

#include <CacKitPlatform.hpp>
#include <Cacao.hpp>
