from Shared import * 

classes = pickle.load(open(picklepath, "rb"))

build_start = """
template<class D>
class ${cl} : public {cl}, public $CacBase {{
public:
    inline ~${cl}() {{}}
"""

build_body1 = """
    using c{id} = {type}({const}${cl}::*)({params3});
    using d{id} = {type}({const}D::*)({params3});
    using f{id} = {type}(*)({const}${cl}*{params2});
    dupable {type} {name}({params}) {const}{{
        {function}
    }}
"""

build_body1_virtual = """
    using c{id} = {type}({const}${cl}::*)({params3});
    using d{id} = {type}({const}D::*)({params3});
    using f{id} = {type}(*)({const}${cl}*{params2});
    dupable {type} {name}({params}) {const}{{
        {function}
    }}
"""

build_body1_static = """
    using c{id} = {type}(*)({params3});
    using d{id} = {type}(*)({params3});
    using f{id} = {type}(*)({params3});
    dupable static {type} {name}({params}) {const}{{
        {function}
    }}
"""

# build_body1 = """
#     using c{id} = {type}({const}${cl}::*)({params3});
#     using d{id} = typename GetDerived<c{id}, D>::type;
#     using f{id} = typename GetStatic<c{id}>::type;
#     dupable {type} {name}({params}) {const}{{
#         {function}
#     }}
# """

# build_body1_virtual = """
#     using c{id} = {type}({const}${cl}::*)({params3});
#     using d{id} = typename GetDerived<c{id}, D>::type;
#     using f{id} = typename GetStatic<c{id}>::type;
#     dupable {type} {name}({params}) {const}{{
#         {function}
#     }}
# """

# build_body1_static = """
#     using c{id} = {type}(*)({params3});
#     using d{id} = {type}(*)({params3});
#     using f{id} = {type}(*)({params3});
#     dupable static {type} {name}({params}) {const}{{
#         {function}
#     }}
# """

build_body2_start = """
    inline ${cl}(bool) {{}}
    inline ${cl}() {{
        auto i = new D();
        auto V = *rcast<uintptr_t*>(i);
        delete i;
        m->registerHook(extract_destructor(V), +[](){{}});
"""
    

build_body2_body = """
        if ((c{id}){{&${cl}::{name}}} != (d{id}){{&D::{name}}})
            m->registerHook(base+{offset}, extract((d{id}){{&D::{name}}}));
"""

build_body2_body_static = """
        if ((c{id}){{&${cl}::{name}}} != (d{id}){{&D::{name}}})
            m->registerHook(base+{offset}, (d{id}){{&D::{name}}});
"""

build_body2_body_virtual = """
        if ((c{id}){{&${cl}::{name}}} != (d{id}){{&D::{name}}})
            m->registerHook(base+{offset}, extract_virtual(V, (d{id}){{&D::{name}}}));
"""

build_body2_end = "    }\n"
build_end = "};\n"

out = """// 
// Copyright camila314 & alk1m123 2021. 
// Autogenerated using a python script
//
#pragma once
#include <Base/InterfaceBase.hpp>
#define rcast reinterpret_cast
"""
for cl in classes:
    if "cocos2d" in cl.name:
        continue

    out += build_start.format(
        cl=cl.name,
    )

    for i, info in enumerate(cl.info):
        if not isinstance(info, CinnamonFunction) or info.declare.name[1:] in cl.name:
            continue
        body1 = build_body1
        if info.static:
            body1 = build_body1_static
        elif info.virtual:
            body1 = build_body1_virtual

        out += body1.format(
            name = info.declare.name,
            type = info.declare.type,
            cl = cl.name,
            offset = info.offset, 
            params = ', '.join(arg.getExpr(i) for i, arg in enumerate(info.parameters)),
            params2 = (', ' if not info.static and len(info.parameters) > 0 else "") + ', '.join(arg.getType(i) for i, arg in enumerate(info.parameters)),
            params3 = ', '.join(arg.getType(i) for i, arg in enumerate(info.parameters)),
            const = "const " if info.const else "",
            id = i,
            function = getFunctionImplementation(cl, info, i),
        )

    out += build_body2_start.format(cl=cl.name)

    for i, info in enumerate(cl.info):
        if not isinstance(info, CinnamonFunction) or info.declare.name[1:] in cl.name:
            continue
        body2 = build_body2_body
        if info.static:
            body2 = build_body2_body_static
        elif info.virtual:
            body2 = build_body2_body_virtual
        out += body2.format(
            name = info.declare.name,
            type = info.declare.type,
            cl = cl.name,
            offset = info.offset, 
            params = ', '.join(arg.getType(i) for i, arg in enumerate(info.parameters)),
            const = "const " if info.const else "",
            id = i,
        )

    out += build_body2_end
    out += build_end

out += """
#undef rcast
"""

with open(os.path.join(os.path.dirname(__file__), "..", "Interface.hpp"), "w") as f:
    f.write(out)
